#runs-on: self-hosted #GOES IN EACH JOB


name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:

    newjob:
        runs-on: self-hosted
        steps:
          - name: Use my action
            uses: gdsmith1/githubExercise2/.github/actions@v8
            with:
              user-input: 'Hello world!'
              
          - name: Download artifact
            uses: actions/download-artifact@v4
            with:
              name: hello2
              path: .
          
          - name: Read artifact
            run: cat hello.txt

         


