#runs-on: self-hosted #GOES IN EACH JOB


name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:

    newjob:
        runs-on: self-hosted
        steps:
          - name: Use my action
            uses: gdsmith1/githubExercise2/.github/actions@v6
            with:
              user-input: 'Hello world!'
              
          - name: Download artifact
            uses: actions/download-artifact@v4
            with:
              name: hello
              path: .
          
          - name: Read artifact
            run: cat hello.txt







    helloworld:
        runs-on: self-hosted
        steps:
            - name: Hello World
              run: echo "Hello World" >> oldhello.txt


            - name: Add oldhello.txt to artifacts
              uses: actions/upload-artifact@v4
              with:
                name: oldhello
                path: oldhello.txt

    artifactReader:
        runs-on: self-hosted
        needs: helloworld
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: oldhello
                path: .

            - name: Read artifact
              run: cat oldhello.txt

            - name: Put hello.txt in an environment variable
              run: |
                value=`cat oldhello.txt`
                echo "HELLO=value" >> $GITHUB_ENV

            - name: Print environment variable
              run: echo $HELLO


    hello_world_job:
      runs-on: ubuntu-latest
      name: A job to say hello
      steps:
        - uses: actions/checkout@v4
        - id: foo
          uses: gdsmith1/githubExercise2/.github/actions@v5
          with:
            who-to-greet: 'Mona the Octocat'
        - run: echo random-number "$RANDOM_NUMBER"
          shell: bash
          env:
            RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}